### ISSUE TITLE
[NEW]: Recommend Bookmark Toolbar

### ISSUE THREAD

**Issue by nuggetsnegin** [mozilla-l10n/nimbus-l10n#42] opened 2024-10-15 21:37 UTC
### Information about the experiment

Two experiments (early day and existing) with 3 treatment branches recommending the user to set their bookmark toolbar visibility to "always", they use the same copy and designs so I filed one request since the translations will be shared but let me know if this should be split into two separate requests. 

[Experiment Brief](https://docs.google.com/document/d/1mKXnU-qbStb1OUNHmDOQY5Awb-Wz5e8wit28jkUKP-4/edit#heading=h.uoblsnu302hk)
[Figma Designs](https://www.figma.com/design/V2alIUZh1C4UXoWacJjZCA/Bookmarks-improvements?node-id=2418-5454&node-type=frame&t=yXRpQavvJl25GGbF-0)
[Nimbus: Recommend Bookmark Toolbar - Existing User](https://experimenter.services.mozilla.com/nimbus/recommend-bookmark-toolbar-existing-user/summary)
[Nimbus: Recommend Bookmark Toolbar - Early Day](https://experimenter.services.mozilla.com/nimbus/recommend-bookmark-toolbar-early-day/summary)

### List of locales

EN-*, FR, IT, DE

### Deadline

2024-10-21

### Content to translate

The messages are quite large and take up quite a bit of the view port (something which was brought up during user testing). If feasible, would lean towards shorter translations but there are no length limitations.

```
{
    "treatment-a-screen-1-title": {
        "$l10n": {
            "id": "treatment-a-screen-1-title",
            "text": "Add this site to your bookmarks toolbar?",
            "comment": ""
        }
    },
    "treatment-a-screen-1-subtitle": {
        "$l10n": {
            "id": "treatment-a-screen-1-subtitle",
            "text": "Your bookmark will be saved just below the address bar for quick access.",
            "comment": ""
        }
    },
    "treatment-a-screen-1-primary-button": {
        "$l10n": {
            "id": "treatment-a-screen-1-primary-button",
            "text": "Add bookmark",
            "comment": ""
        }
    },
    "treatment-a-screen-1-secondary-button": {
        "$l10n": {
            "id": "treatment-a-screen-1-secondary-button",
            "text": "No thanks",
            "comment": ""
        }
    },
    "treatment-a-screen-2-accept-title": {
        "$l10n": {
            "id": "treatment-a-screen-2-accept-title",
            "text": "Easily add more bookmarks",
            "comment": ""
        }
    },
    "treatment-a-screen-2-accept-subtitle": {
        "$l10n": {
            "id": "treatment-a-screen-2-accept-subtitle",
            "text": "You can drag and drop tabs here to keep more of your favorite sites within reach.",
            "comment": ""
        }
    },
    "treatment-a-screen-2-accept-primary-button": {
        "$l10n": {
            "id": "treatment-a-screen-2-accept-primary-button",
            "text": "Got it!",
            "comment": ""
        }
    },
    "treatment-a-screen-2-accept-secondary-button": {
        "$l10n": {
            "id": "treatment-a-screen-2-accept-secondary-button",
            "text": "Hide toolbar",
            "comment": ""
        }
    },
    "treatment-a-screen-2-decline-title": {
        "$l10n": {
            "id": "treatment-a-screen-2-decline-title",
            "text": "Keep your bookmarks toolbar open?",
            "comment": ""
        }
    },
    "treatment-a-screen-2-decline-subtitle": {
        "$l10n": {
            "id": "treatment-a-screen-2-decline-subtitle",
            "text": "You can add other sites you visit more often. Simply drag and drop tabs here to keep favorite websites within reach.",
            "comment": ""
        }
    },
    "treatment-a-screen-2-decline-primary-button": {
        "$l10n": {
            "id": "treatment-a-screen-2-decline-primary-button",
            "text": "Keep open",
            "comment": ""
        }
    },
    "treatment-a-screen-2-decline-secondary-button": {
        "$l10n": {
            "id": "treatment-a-screen-2-decline-secondary-button",
            "text": "No thanks",
            "comment": ""
        }
    },
    "treatment-b-title": {
        "$l10n": {
            "id": "treatment-b-title",
            "text": "Keep bookmarks toolbar open?",
            "comment": ""
        }
    },
    "treatment-b-subtitle": {
        "$l10n": {
            "id": "treatment-b-subtitle",
            "text": "Once open, you can drag and drop tabs onto the bookmarks toolbar to keep your favorite sites within reach.",
            "comment": ""
        }
    },
    "treatment-b-primary-button": {
        "$l10n": {
            "id": "treatment-b-primary-button",
            "text": "Keep open",
            "comment": ""
        }
    },
    "treatment-b-secondary-button": {
        "$l10n": {
            "id": "treatment-b-secondary-button",
            "text": "No thanks",
            "comment": ""
        }
    },
    "treatment-c-title": {
        "$l10n": {
            "id": "treatment-c-title",
            "text": "Add this site to your bookmarks toolbar?",
            "comment": ""
        }
    },
    "treatment-c-subtitle": {
        "$l10n": {
            "id": "treatment-c-subtitle",
            "text": "We’ll leave the toolbar open so you can drag tabs here and keep your favorite sites within reach.",
            "comment": ""
        }
    },
    "treatment-c-primary-button": {
        "$l10n": {
            "id": "treatment-c-primary-button",
            "text": "Add bookmark",
            "comment": ""
        }
    },
    "treatment-c-secondary-button": {
        "$l10n": {
            "id": "treatment-c-secondary-button",
            "text": "No thanks",
            "comment": ""
        },
        "split-dismiss-button-option-1": {
            "$l10n": {
                "id": "split-dismiss-button-option-1",
                "text": "Don’t show this recommendation again",
                "comment": ""
            }
        },
        "split-dismiss-button-option-2": {
            "$l10n": {
                "id": "split-dismiss-button-option-2",
                "text": "Show fewer recommendations",
                "comment": ""
            }
        },
        "split-dismiss-button-option-3": {
            "$l10n": {
                "id": "split-dismiss-button-option-3",
                "text": "Manage settings",
                "comment": ""
            }
        }
    }
}
```

**Comment by flodolo** [comment] 2024-10-16 06:04
Redirecting to @bcolsson as I'm out this week, but there are a few issues to solve before this is actionable.

The deadline is too close, as we need time to localize with community on top of the time to set the experiment up. 
Is Oct 21 the expected launch date? Mid-next week is a more realistic deadline.

Per [instructions](https://experimenter.info/localization-process/#multi-locale-recipe-firefox-113-and-later), the strings need to be set up for extraction in the experiment (via automation), pasting them in the issue is not sufficient:
* I briefly checked the experiments, but I don't see the strings set up (as `$l10n`) in either of them? I see hard-coded text.
* Are the two experiments identical and we can set up only one of them? If not, we're going to have duplication (and longer time for localization).

**Comment by nuggetsnegin** [comment] 2024-10-16 13:25
Oh sorry about that! @flodolo I thought I had updated the recipe. I'll do that right now. Both experiments will be the exact same and we only need one set up. We're looking to launch this in Fx132 (October 29), 21st was setup so QA has some extra room for testing but it's not a hard deadline.

**Comment by nuggetsnegin** [comment] 2024-10-16 14:28
Both recipes have been updated with the $l10n objects.

**Comment by bcolsson** [comment] 2024-10-16 17:56
@nuggetsnegin - I attempted to get the automation running, but it looks like the experiments are setup as preview, but the automation expects these to be drafts. Can you change the status of one of these to draft?

**Comment by mozilla-pontoon** [comment] 2024-10-16 18:05
Created pull request: https://github.com/mozilla-l10n/nimbus-l10n/pull/46

**Comment by bcolsson** [comment] 2024-10-16 18:08
(Ignore previous comment, was able to move back to draft myself)

**Comment by mozilla-pontoon** [comment] 2024-10-24 16:03
Translation has been completed for `recommend_bookmark_toolbar_existing_user_2024.ftl`.

Here’s the data to copy in the Localization field in Experimenter:

```
{
  "de": {
    "split-dismiss-button-option-1": "Diese Empfehlung nicht mehr anzeigen",
    "split-dismiss-button-option-2": "Weniger Empfehlungen anzeigen",
    "split-dismiss-button-option-3": "Einstellungen verwalten",
    "treatment-a-screen-1-primary-button": "Lesezeichen hinzufügen",
    "treatment-a-screen-1-secondary-button": "Nein danke",
    "treatment-a-screen-1-subtitle": "Ein Lesezeichen wird direkt unter der Adressleiste gespeichert, damit du schnell darauf zugreifen zu kannst.",
    "treatment-a-screen-1-title": "Diese Website zur Lesezeichen-Symbolleiste hinzufügen?",
    "treatment-a-screen-2-accept-primary-button": "Alles klar!",
    "treatment-a-screen-2-accept-secondary-button": "Symbolleiste ausblenden",
    "treatment-a-screen-2-accept-subtitle": "Zieh Tabs hierher und lege sie ab, um weitere deiner Lieblings-Webseiten griffbereit zu haben.",
    "treatment-a-screen-2-accept-title": "Einfach weitere Lesezeichen hinzufügen",
    "treatment-a-screen-2-decline-primary-button": "Offen lassen",
    "treatment-a-screen-2-decline-secondary-button": "Nein danke",
    "treatment-a-screen-2-decline-subtitle": "Füge andere Webseiten hinzu, die du häufiger besuchst. Ziehen Tabs hierher und lege sie ab, um deine Lieblings-Webseiten griffbereit zu haben.",
    "treatment-a-screen-2-decline-title": "Lesezeichen-Symbolleiste geöffnet lassen?",
    "treatment-b-primary-button": "Offen lassen",
    "treatment-b-secondary-button": "Nein danke",
    "treatment-b-subtitle": "Ziehe Tabs auf die offene Lesezeichen-Symbolleiste und lege sie ab, um deine Lieblings-Webseiten immer griffbereit zu haben.",
    "treatment-b-title": "Lesezeichen-Symbolleiste geöffnet lassen?",
    "treatment-c-primary-button": "Lesezeichen hinzufügen",
    "treatment-c-secondary-button": "Nein danke",
    "treatment-c-subtitle": "Wir lassen die Symbolleiste geöffnet, damit du Tabs dorthin ziehen kannst und so deine Lieblings-Webseiten immer griffbereit sind.",
    "treatment-c-title": "Diese Website zur Lesezeichen-Symbolleiste hinzufügen?"
  },
  "en-CA": {
    "split-dismiss-button-option-1": "Don’t show this recommendation again",
    "split-dismiss-button-option-2": "Show fewer recommendations",
    "split-dismiss-button-option-3": "Manage settings",
    "treatment-a-screen-1-primary-button": "Add bookmark",
    "treatment-a-screen-1-secondary-button": "No thanks",
    "treatment-a-screen-1-subtitle": "Your bookmark will be saved just below the address bar for quick access.",
    "treatment-a-screen-1-title": "Add this site to your bookmarks toolbar?",
    "treatment-a-screen-2-accept-primary-button": "Got it!",
    "treatment-a-screen-2-accept-secondary-button": "Hide toolbar",
    "treatment-a-screen-2-accept-subtitle": "You can drag and drop tabs here to keep more of your favorite sites within reach.",
    "treatment-a-screen-2-accept-title": "Easily add more bookmarks",
    "treatment-a-screen-2-decline-primary-button": "Keep open",
    "treatment-a-screen-2-decline-secondary-button": "No thanks",
    "treatment-a-screen-2-decline-subtitle": "You can add other sites you visit more often. Simply drag and drop tabs here to keep favorite websites within reach.",
    "treatment-a-screen-2-decline-title": "Keep your bookmarks toolbar open?",
    "treatment-b-primary-button": "Keep open",
    "treatment-b-secondary-button": "No thanks",
    "treatment-b-subtitle": "Once open, you can drag and drop tabs onto the bookmarks toolbar to keep your favorite sites within reach.",
    "treatment-b-title": "Keep bookmarks toolbar open?",
    "treatment-c-primary-button": "Add bookmark",
    "treatment-c-secondary-button": "No thanks",
    "treatment-c-subtitle": "We’ll leave the toolbar open so you can drag tabs here and keep your favorite sites within reach.",
    "treatment-c-title": "Add this site to your bookmarks toolbar?"
  },
  "en-GB": {
    "split-dismiss-button-option-1": "Don’t show this recommendation again",
    "split-dismiss-button-option-2": "Show fewer recommendations",
    "split-dismiss-button-option-3": "Manage settings",
    "treatment-a-screen-1-primary-button": "Add bookmark",
    "treatment-a-screen-1-secondary-button": "No thanks",
    "treatment-a-screen-1-subtitle": "Your bookmark will be saved just below the address bar for quick access.",
    "treatment-a-screen-1-title": "Add this site to your bookmarks toolbar?",
    "treatment-a-screen-2-accept-primary-button": "Got it!",
    "treatment-a-screen-2-accept-secondary-button": "Hide toolbar",
    "treatment-a-screen-2-accept-subtitle": "You can drag and drop tabs here to keep more of your favorite sites within reach.",
    "treatment-a-screen-2-accept-title": "Easily add more bookmarks",
    "treatment-a-screen-2-decline-primary-button": "Keep open",
    "treatment-a-screen-2-decline-secondary-button": "No thanks",
    "treatment-a-screen-2-decline-subtitle": "You can add other sites you visit more often. Simply drag and drop tabs here to keep favorite websites within reach.",
    "treatment-a-screen-2-decline-title": "Keep your bookmarks toolbar open?",
    "treatment-b-primary-button": "Keep open",
    "treatment-b-secondary-button": "No thanks",
    "treatment-b-subtitle": "Once open, you can drag and drop tabs onto the bookmarks toolbar to keep your favorite sites within reach.",
    "treatment-b-title": "Keep bookmarks toolbar open?",
    "treatment-c-primary-button": "Add bookmark",
    "treatment-c-secondary-button": "No thanks",
    "treatment-c-subtitle": "We’ll leave the toolbar open so you can drag tabs here and keep your favorite sites within reach.",
    "treatment-c-title": "Add this site to your bookmarks toolbar?"
  },
  "en-US": {
    "split-dismiss-button-option-1": "Don’t show this recommendation again",
    "split-dismiss-button-option-2": "Show fewer recommendations",
    "split-dismiss-button-option-3": "Manage settings",
    "treatment-a-screen-1-primary-button": "Add bookmark",
    "treatment-a-screen-1-secondary-button": "No thanks",
    "treatment-a-screen-1-subtitle": "Your bookmark will be saved just below the address bar for quick access.",
    "treatment-a-screen-1-title": "Add this site to your bookmarks toolbar?",
    "treatment-a-screen-2-accept-primary-button": "Got it!",
    "treatment-a-screen-2-accept-secondary-button": "Hide toolbar",
    "treatment-a-screen-2-accept-subtitle": "You can drag and drop tabs here to keep more of your favorite sites within reach.",
    "treatment-a-screen-2-accept-title": "Easily add more bookmarks",
    "treatment-a-screen-2-decline-primary-button": "Keep open",
    "treatment-a-screen-2-decline-secondary-button": "No thanks",
    "treatment-a-screen-2-decline-subtitle": "You can add other sites you visit more often. Simply drag and drop tabs here to keep favorite websites within reach.",
    "treatment-a-screen-2-decline-title": "Keep your bookmarks toolbar open?",
    "treatment-b-primary-button": "Keep open",
    "treatment-b-secondary-button": "No thanks",
    "treatment-b-subtitle": "Once open, you can drag and drop tabs onto the bookmarks toolbar to keep your favorite sites within reach.",
    "treatment-b-title": "Keep bookmarks toolbar open?",
    "treatment-c-primary-button": "Add bookmark",
    "treatment-c-secondary-button": "No thanks",
    "treatment-c-subtitle": "We’ll leave the toolbar open so you can drag tabs here and keep your favorite sites within reach.",
    "treatment-c-title": "Add this site to your bookmarks toolbar?"
  },
  "fr": {
    "split-dismiss-button-option-1": "Ne plus afficher cette recommandation",
    "split-dismiss-button-option-2": "Afficher moins de recommandations",
    "split-dismiss-button-option-3": "Gérer les paramètres",
    "treatment-a-screen-1-primary-button": "Ajouter le marque-page",
    "treatment-a-screen-1-secondary-button": "Non merci",
    "treatment-a-screen-1-subtitle": "Votre marque-page sera enregistré juste en dessous de la barre d’adresse pour pouvoir y accéder rapidement.",
    "treatment-a-screen-1-title": "Ajouter ce site à la barre personnelle ?",
    "treatment-a-screen-2-accept-primary-button": "J’ai compris",
    "treatment-a-screen-2-accept-secondary-button": "Masquer la barre personnelle",
    "treatment-a-screen-2-accept-subtitle": "Vous pouvez glisser-déposer des onglets ici pour garder davantage de vos sites préférés à portée de main.",
    "treatment-a-screen-2-accept-title": "Ajoutez facilement des marque-pages",
    "treatment-a-screen-2-decline-primary-button": "La garder ouverte",
    "treatment-a-screen-2-decline-secondary-button": "Non merci",
    "treatment-a-screen-2-decline-subtitle": "Vous pouvez ajouter d’autres sites que vous visitez souvent. Glissez-déposez simplement des onglets ici pour garder vos sites web préférés à portée de main.",
    "treatment-a-screen-2-decline-title": "Laisser la barre personnelle ouverte ?",
    "treatment-b-primary-button": "La garder ouverte",
    "treatment-b-secondary-button": "Non merci",
    "treatment-b-subtitle": "Une fois ouverte, vous pouvez glisser-déposer des onglets dans la barre personnelle pour garder vos sites préférés à portée de main.",
    "treatment-b-title": "Laisser la barre personnelle ouverte ?",
    "treatment-c-primary-button": "Ajouter le marque-page",
    "treatment-c-secondary-button": "Non merci",
    "treatment-c-subtitle": "Nous laisserons la barre personnelle ouverte afin que vous puissiez faire glisser des onglets ici et garder vos sites préférés à portée de main.",
    "treatment-c-title": "Ajouter ce site à la barre personnelle ?"
  },
  "it": {
    "split-dismiss-button-option-1": "Non mostrare di nuovo questo suggerimento",
    "split-dismiss-button-option-2": "Mostra meno suggerimenti",
    "split-dismiss-button-option-3": "Gestisci impostazioni",
    "treatment-a-screen-1-primary-button": "Aggiungi segnalibro",
    "treatment-a-screen-1-secondary-button": "No grazie",
    "treatment-a-screen-1-subtitle": "Il segnalibro verrà salvato appena sotto la barra degli indirizzi, così da offrirti un accesso più rapido.",
    "treatment-a-screen-1-title": "Aggiungere questo sito alla barra dei segnalibri?",
    "treatment-a-screen-2-accept-primary-button": "OK",
    "treatment-a-screen-2-accept-secondary-button": "Nascondi barra",
    "treatment-a-screen-2-accept-subtitle": "Puoi trascinare le schede qui per tenere a portata di mano i tuoi siti preferiti.",
    "treatment-a-screen-2-accept-title": "Aggiungi facilmente altri segnalibri",
    "treatment-a-screen-2-decline-primary-button": "Mantieni aperta",
    "treatment-a-screen-2-decline-secondary-button": "No grazie",
    "treatment-a-screen-2-decline-subtitle": "Puoi aggiungere gli altri siti che visiti più spesso. Basta trascinare le schede qui per mantenere i tuoi siti web preferiti a portata di mano.",
    "treatment-a-screen-2-decline-title": "Mantenere aperta la barra dei segnalibri?",
    "treatment-b-primary-button": "Mantieni aperta",
    "treatment-b-secondary-button": "No grazie",
    "treatment-b-subtitle": "Quando è aperta, puoi trascinare le schede nella barra dei segnalibri per mantenere i tuoi siti preferiti sempre a portata di mano.",
    "treatment-b-title": "Mantenere aperta la barra dei segnalibri?",
    "treatment-c-primary-button": "Aggiungi segnalibro",
    "treatment-c-secondary-button": "No grazie",
    "treatment-c-subtitle": "Manterremo aperta la barra degli strumenti, così potrai trascinarvi le schede e mantenere i tuoi siti preferiti a portata di mano.",
    "treatment-c-title": "Aggiungere questo sito alla barra dei segnalibri?"
  }
}
```

**Comment by nuggetsnegin** [comment] 2024-10-30 16:55
Thanks! Assuming I can mark this as closed?

**Comment by bcolsson** [comment] 2024-10-30 16:58
> Thanks! Assuming I can mark this as closed?

Thanks for following up. Yes! I can close this now, but next time please feel free to close when you take the translations and everything looks good on your end.

**Closed by bcolsson** 2024-10-30 16:58 UTC
